export const properties = [
  {
    id: 1,
    image: "/images/property/1.jpg",
    name: "10765 Hillshire Ave, Baton Rouge, LA 70810, USA",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5.0,
    detail: [
      "/images/property/single/1.jpg",
      "/images/property/single/2",
      "/images/property/single/3",
      "/images/property/single/4.jpg",
      "/images/property/single/5.jpg",
    ],
  },
  {
    id: 2,
    image: "/images/property/2.jpg",
    name: "59345 STONEWALL DR, Plaquemine, LA 70764, USA",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5.0,
    detail: [
      "/images/property/single/1.jpg",
      "/images/property/single/2",
      "/images/property/single/3",
      "/images/property/single/4.jpg",
      "/images/property/single/5.jpg",
    ],
  },
  {
    id: 3,
    image: "/images/property/2.jpg",
    name: "3723 SANDBAR DR, Addis, LA 70710, USA",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5.0,
    detail: [
      "/images/property/single/1.jpg",
      "/images/property/single/2",
      "/images/property/single/3",
      "/images/property/single/4.jpg",
      "/images/property/single/5.jpg",
    ],
  },
  {
    id: 4,
    image: "/images/property/2.jpg",
    name: "Lot 21 ROYAL OAK DR, Prairieville, LA 70769, USA",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5.0,
    detail: [
      "/images/property/single/1.jpg",
      "/images/property/single/2",
      "/images/property/single/3",
      "/images/property/single/4.jpg",
      "/images/property/single/5.jpg",
    ],
  },
  {
    id: 5,
    image: "/images/property/2.jpg",
    name: "710 BOYD DR, Unit #1102, Baton Rouge, LA 70808, USA",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5.0,
    detail: [
      "/images/property/single/1.jpg",
      "/images/property/single/2",
      "/images/property/single/3",
      "/images/property/single/4.jpg",
      "/images/property/single/5.jpg",
    ],
  },
  {
    id: 6,
    image: "/images/property/2.jpg",
    name: "5133 MCLAIN WAY, Baton Rouge, LA 70809, USA",
    square: 8000,
    beds: 4,
    baths: 4,
    price: 5000,
    rating: 5.0,
    detail: [
      "/images/property/single/1.jpg",
      "/images/property/single/2",
      "/images/property/single/3",
      "/images/property/single/4.jpg",
      "/images/property/single/5.jpg",
    ],
  },
];
